version: "3"
services:
  # prod:
  #   restart: always
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   container_name: hr-bot
  #   depends_on:
  #     - mongo
  #   volumes:
  #     - type: bind
  #       source: ./model-q4_K.gguf
  #       target: /model-q4_K.gguf
  mongo:
    restart: always
    image: mongo:latest
    container_name: hr-bot-mongo
    env_file:
      - .env
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - mongo-data:/data/db
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_storage:/qdrant/storage:z
volumes:
  mongo-data:
    driver: local
